### ISSUE TITLE
Связь между шаблоном и компонентом

### ISSUE THREAD

**Issue by ildar-ceo** [bayrell/Bayrell.Lang#27]
Есть проблема связи между шаблоном и экземпляром компонента.
Как найти инстанс компонента и функцию onClick?
```
<Button @eventAsync:MouseClickEvent="onClick"}>ClickMe</Button>
```
Сейчас это решается через поиск компонента по его классу по виртуальному пути. Каждый элемент имеет свой путь. В этом пути ищется компонент по его названию.
А как это сделать более лаконично?

**Comment by vistoyn** [comment]
Иногда возникают ситуации, когда вышестоящий компонент должен отправить событие нижестоящему компоненту.

**Comment by vistoyn** [comment]
Найти инстанс компонента по его имени можно:
```
Component c = this.driver.findComponents(class_name)[0];
```

**Comment by ildar-ceo** [comment]
```
<Button @event:MouseClickEvent={ component.onClick(msg) }>ClickMe</Button>
```
