### ISSUE TITLE
Обработка событий в RenderDriver. Глобальные события

### ISSUE THREAD

**Issue by ildar-ceo** [bayrell/Bayrell.Lang#28]
Как компонент может подписаться на события в нижестоящих компонентов. Или вообще другом компоненте?
Как отправить событие определенному компоненту?
Как отправить глобальное событие?

**Comment by vistoyn** [comment]
Render функция переписана, поэтому надо думать как отправлять глобальные события.

**Comment by ildar-ceo** [comment]
Было решено использовать Vue.js
