### ISSUE TITLE
Virtual DOM на базе Runtime.Web.Element

### ISSUE THREAD

**Issue by ildar-ceo** [bayrell/Bayrell.Lang#68]
Нужно сделать Shadow DOM, чтобы Runtime.Web.Controller проверял Shadow DOM, а не реальный. И на основе diff патчил реальный DOM.
Затем нужно добавить функции для изменения Shadow DOM из компонентов, с последующим вызовом request Animation Frame, например для анимации.

**Comment by vistoyn** [comment]
В Shadow DOM, помимо html node должны храниться компоненты

**Comment by vistoyn** [comment]
Virtual Dom Tree - виртуальное дерево, которое отображает DOM. Элементами дерева являются: элементы, компоненты, рендер функции.
Функция рендера должна на вход принимать old virtual tree и возвращать набор патчей, для перехода в new virtual tree. На основе этих патчей создается новое дерево, а также идет патч DOM.
Virtual Dom Tree нужен, чтобы быстро анализировать элементы, без сканирования реального DOM.

Создание патча должно происходить методом поиска в ширину. Должно быть четкое определение от каких model path зависит ветка. Если произошли изменения в model path, то ветку нужно обойти, либо перейти именно к этим изменениям. Если изменений в модели не было, то нужно возвратить старое дерево.

**Comment by vistoyn** [comment]
Должна быть возможность вызова кастомной рендер функции, которая вернет набор команд для патча.
Например, из js вызываем component::renderItem() передаем туда необходимые параметры и возрашается diff для DOM, который потом применяем.

**Comment by vistoyn** [comment]
Рендер должен происходить следующим образом:
1) Сначала полностью рендерится вся страница
2) Затем происходят события на страницы, и программист сам прописывает логику изменения интерфейса.
3) Возможно нужен обмен событиями

Также должен быть глобальное событие repaint, которое перерисует и пропатчит весь интерфейс

**Comment by vistoyn** [comment]
```
<class>


<template>

<Label @name="label" text="" />

<List @name="list" items={ model.items }
	@event:onSelectItem="onListSelectItem"
/>

<Form @name="form" />

</template>


<script>

void onListSelectItem(Message<onSelectItem> msg)
{
	int index = msg.data.index;
	Item item = this.model(["items", index]);
	this.form.updateItem(item);
	this.label.setLabel("Selected: " + item.name);
}

</script>


</class>
```

**Comment by vistoyn** [comment]
У компонента должны быть функция repaint, которая перерисует этот компонент.
А также частные функции, которые изменяют DOM.
Например, функция this.dialog.show() должна:
1) Изменить глобальную модель, поменять в модели диалогового окна is_open на true
2) Отправить Virtual DOM патч, который ставит css стиль display: block;
3) Отправить глобальное сообщение, DialogEvent с action="show"

**Comment by vistoyn** [comment]
Если в компоненте прописано @event:DialogEvent="onDialogEvent"
То:
1) Компонент слушает все глобальные события
2) Он просматривает, какой компонент послал событие, если это подкомпонент, на который он подписан, и класс события совпадает, то вызвать функцию onDialogEvent

**Comment by vistoyn** [comment]
Функция repaint должна вызываться при перерисовке большей части страницы, например, при смене страницы. А если открылось диалоговое окно. То достаточно сделать патч Virtual Dom
